---
- name: setup nodejs6.x
  become: yes
  shell: curl -sL https://rpm.nodesource.com/setup_6.x | sudo -E bash -
- name: installing latest version of node.js
  become: yes
  yum:
    name: nodejs
    state: latest

- name: Install "executor" node.js package.
  npm:
    name: '@lassehaslev/executor'
    global: true

- name: put "tdd command"
  template: 'src=tdd dest={{ homedir }}/apps/myapp/tdd'

- name: chmod "tdd"
  command: 'chmod 755 {{ homedir }}/apps/myapp/tdd'

