####
# Laravel動かすためにSELinuxを無効化したほうがよさげ
####
- name: install libselinux-python
  yum: name=libselinux-python state=latest

- name: disable SELinux
  selinux: state=disabled

- name: check project-myapp
  stat:
    path: "{{ homedir }}/apps/myapp"
  register: check_myapp

- name: create-laravel myapp
  composer:
    command: create-project
    arguments: laravel/laravel myapp 5.5.*
    working_dir: "{{ homedir }}/apps"
    prefer_dist: yes
  when: not check_myapp.stat.exists

- name: composer-self update
  composer:
    command: self-update
    working_dir: "{{ homedir }}/apps/myapp"

- name: composer-install myapp
  composer:
    command: install
    optimize-autoloader: yes
    working_dir: "{{ homedir }}/apps/myapp"

- name: rewrite .env
  lineinfile:
    dest={{ homedir }}/apps/myapp/.env
    state=present
    backrefs=yes
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: 'DB_DATABASE=homestead'
      line: 'DB_DATABASE=localdb'
    - regexp: 'DB_USERNAME=homestead'
      line: 'DB_USERNAME=root'
    - regexp: 'DB_PASSWORD=secret'
      line: 'DB_PASSWORD={{ mysql_root_passwd }}'

