#!/bin/sh

function usage {
    cat <<EOF
    $(basename ${0}) is a tool for phpunit or phpstan (or all) watching executor
Usage:
    $(basename ${0}) phpunit|phpstan|all
Options:
    --help, -h        print this
EOF
}

phpunit="./vendor/bin/phpunit" 
phpstan="./vendor/bin/phpstan analyze -c phpstan.neon -l 1 --no-progress app routes"
params=" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'"

case ${1} in

    phpunit)
        executor $phpunit $params
    ;;

    phpstan)
        executor $phpstan $params
    ;;

    all)
        executor "$phpunit && $phpstan" $params
    ;;

    help|--help|-h)
        usage
    ;;

    *)
        executor "$phpunit && $phpstan" $params
    ;;
esac
