---
- hosts: vagrants
  become: true
  user: vagrant
  vars:
    srcpath: /usr/local/src
    homedir: /home/vagrant
    tmp: /tmp
    mysql_root_passwd: RootPass4Local$
  tasks:
    - name: install packages zsh
      ping:
  roles:
    - { role: git, tags: ["local"] }
    - { role: php7, tags: ["local"] }
    - { role: apache2_4, tags: ["local"] }
    - { role: laravel, tags: ["local"] }
    - { role: mysql57, tags: ["local"] }
